spring.application.name=asset-audit-system

# Server Configuration
server.port=8080

# PostgreSQL Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/asset_audit_db
spring.datasource.username=postgres
spring.datasource.password=141017

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true